"""Initial migration - create all tables

Revision ID: 4649e02d2550
Revises: 
Create Date: 2025-09-03 16:16:30.538389-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4649e02d2550'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('papel', sa.String(length=100), nullable=False),
    sa.Column('google_connected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=True),
    sa.Column('data_inicio_contrato', sa.Date(), nullable=True),
    sa.Column('data_reuniao_inicial', sa.Date(), nullable=True),
    sa.Column('contatos_empresa', sa.JSON(), nullable=True),
    sa.Column('canais', sa.JSON(), nullable=True),
    sa.Column('autorizacoes_documentos', sa.JSON(), nullable=True),
    sa.Column('status_onboarding', sa.Enum('INICIADO', 'REUNIAO_AGENDADA', 'DOCUMENTACAO', 'REVISAO', 'CONCLUIDO', name='status_onboarding_enum'), nullable=True),
    sa.Column('status_relacionamento', sa.Enum('ATIVO', 'INATIVO', 'PENDENTE', 'ENCERRADO', name='status_relacionamento_enum'), nullable=True),
    sa.Column('data_encerramento', sa.Date(), nullable=True),
    sa.Column('responsavel_followup_id', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsavel_followup_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_cnpj'), 'clientes', ['cnpj'], unique=False)
    op.create_index(op.f('ix_clientes_id'), 'clientes', ['id'], unique=False)
    op.create_table('google_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_google_tokens_id'), 'google_tokens', ['id'], unique=False)
    op.create_table('agendamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('REUNIAO_INICIAL', 'D15', 'D50', 'FOLLOWUP', 'VISITA_TECNICA', name='tipo_agendamento_enum'), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=False),
    sa.Column('data_agendada', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONCLUIDO', 'CANCELADO', 'REAGENDADO', name='status_agendamento_enum'), nullable=True),
    sa.Column('google_event_id', sa.String(length=255), nullable=True),
    sa.Column('google_calendar_id', sa.String(length=255), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('local', sa.String(length=500), nullable=True),
    sa.Column('link_reuniao', sa.String(length=500), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendamentos_id'), 'agendamentos', ['id'], unique=False)
    op.create_table('contatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('REUNIAO_INICIAL', 'D15', 'D50', 'FOLLOWUP', 'SUPORTE', name='tipo_contato_enum'), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=True),
    sa.Column('hora_fim', sa.Time(), nullable=True),
    sa.Column('participantes', sa.JSON(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('canal', sa.Enum('PRESENCIAL', 'VIDEOCHAMADA', 'TELEFONE', 'EMAIL', 'WHATSAPP', name='canal_contato_enum'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contatos_id'), 'contatos', ['id'], unique=False)
    op.create_table('visitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('local', sa.String(length=500), nullable=False),
    sa.Column('tipo_visita', sa.Enum('INSTALACAO', 'MANUTENCAO', 'TREINAMENTO', 'AUDITORIA', 'CONSULTORIA', name='tipo_visita_enum'), nullable=False),
    sa.Column('pauta', sa.JSON(), nullable=True),
    sa.Column('assuntos', sa.JSON(), nullable=True),
    sa.Column('decisoes', sa.JSON(), nullable=True),
    sa.Column('pendencias', sa.JSON(), nullable=True),
    sa.Column('satisfacao', sa.Integer(), nullable=True),
    sa.Column('participantes', sa.JSON(), nullable=True),
    sa.Column('anexos', sa.JSON(), nullable=True),
    sa.Column('assinaturas', sa.JSON(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitas_id'), 'visitas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitas_id'), table_name='visitas')
    op.drop_table('visitas')
    op.drop_index(op.f('ix_contatos_id'), table_name='contatos')
    op.drop_table('contatos')
    op.drop_index(op.f('ix_agendamentos_id'), table_name='agendamentos')
    op.drop_table('agendamentos')
    op.drop_index(op.f('ix_google_tokens_id'), table_name='google_tokens')
    op.drop_table('google_tokens')
    op.drop_index(op.f('ix_clientes_id'), table_name='clientes')
    op.drop_index(op.f('ix_clientes_cnpj'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
